UCS_DB_LINK = "https://www.ucsusa.org/resources/satellite-database"
CELESTRAK_SATCAT_CSV = "https://celestrak.org/pub/satcat.csv"
WIKI_SEARCH_URL = "https://en.wikipedia.org/w/api.php"
WIKI_SUMMARY_URL = "https://en.wikipedia.org/api/rest_v1/page/summary/{}"
NEXTSPACEFLIGHT_LAUNCHES_URL = "https://nextspaceflight.com/launches/"
PLANET4589_LV_URL = "https://www.planet4589.org/space/gcat/data/tables/lv.html"

INPUT_REQUIRED_COLUMNS = [
    "SATNAME",
    "NORAD_ CAT_ID",
    "INTLDES",
    "RA NAME",
]

DATA_COLUMNS = [
    "RA NAME",
    "INTLDES",
    "SATELLITE CODE",
    "OBJECT_ TYPE",
    "SATNAME",
    "MISSION NAME",
    "VEHICLE TYPE NAME",
    "REGION",
    "COUNTRY",
    "LAUNCH DATE",
    "LAUNCH_ YEAR",
    "LAUNCH_ NUM",
    "LAUNCH_ PIECE",
    "SITE",
    "DECAY",
    "PERIOD",
    "INCLINATION",
    "APOGEE",
    "PERIGEE",
    "RCS_SIZE",
    "ALTITUDE",
    "ORBITAL LIFE YEARS (right in numbers, no need to write any text- in yrs)",
    "Launch Orbit Classification (ISRO)",
    "No. of payloads",
    "Type of Satellite (Communication/ Earth Observation / Experimental / Navigation / Science & Exploration)",
    "Satellite Application Description",
    "Satellite Application Source",
    "Sensor Specifications (if applicable)",
    "Spectral Bands",
    "Spatial Resolution",
    "Technological breakthroughs",
    "Technological Breakthroughs Source",
    "Max Launch Mass of Vehicle to LEO (Kg)",
    "Max Launch Mass Reference",
    "Actual Launch Mass Carried by the Vehicle (Kg)",
    "Actual Launch Mass Reference",
    "LAUNCH SUCCESS (1) / FAILURE (0)",
    "VEHICLE RESUABILITY (0/1)",
    "Vehicle Resubaility Details (First stage/ second stage/ or more)",
    "Vehicle Resuability Source",
    "MISSION COST (Overall Mission Cost, Vehicle (Launch) Cost, Development Cost, Approved Cost, Operational Cost) by Official instutiuons or Space Agencies",
    "Mission Cost Source",
    "SATELLITE Vehicle Launch Cost by NextSpaceFlight (in $ million) in launch year",
    "Launch Vehicle Cost Source",
    "SATELLITE Cost by Govt/ Parliament/ Space Agency (in $ million) in launch year",
    "Satellite Development Cost Source",
    "MISSION/SATELLITE Cost by Other / News/ Wiklipedia sources (in $ million) in launch year",
    "Other Reported Cost Source",
    "COST Reference",
    "Other Insights/ Comments",
]

GPT_COLUMNS = [
    "RA Name",
    "INTLDES",
    "NORAD_ CAT_ID",
    "OBJECT_ TYPE",
    "SATNAME",
    "MISSION NAME",
    "VEHICLE TYPE NAME",
    "REGION",
    "COUNTRY",
    "LAUNCH DATE",
    "USER",
    "USER CATEGORY NUMBER",
    "USER DESCRIPTION",
    "USER SOURCE LINK",
    "PURPOSE",
    "PURPOSE CATEGORY NUMBER",
    "PURPOSE DESCRIPTION",
    "PURPOSE SOURCE LINK",
    "SDG CATEGORY",
    "SDG CATEGORY IDENTIFICATION NUMBERS",
    "SDG DESCRIPTION",
    "SDG SOURCE LINK",
    "FRUGAL (YES/ NO)",
    "Development Cost Efficiency (0/1)",
    "Development Cost Efficiency Description",
    "Dev cost efficiency source",
    "Operational Cost Efficiency (0/1)",
    "Operational Cost Efficiency Description",
    "ops cost efficiency source",
    "Labour Cost Efficiency (0/1)",
    "Labour Cost Efficiency Description",
    "Labour cost efficiency source",
    "Frugal Innovation Design (0/1)",
    "Frugal Innovation Design Description",
    "frugal innovation design source",
    "Return on Investment Data of Revenue from Satellite Launch ($ million)",
    "Return on Investment Description",
    "Source",
    "TIP",
    "TIP Description",
    "TIP Source",
    "NIS",
    "NIS Description",
    "NIS Source",
    "MATCH TYPE",
    "MATCH SCORE",
    "CONFIDENCE",
    "REVIEW STATUS",
    "EXTRACTION DATE",
]

NUMERIC_COLUMNS = [
    "SATNAME",
    "NORAD_ CAT_ID",
    "SOURCE LINK",
    "PAYLOAD INNOVATION SCORE",
    "PAYLOAD INNOVATION JUSTIFICATION",
    "SPECTRAL BAND INNOVATION SCORE",
    "SPECTRAL BAND INNOVATION JUSTIFICATION",
    "SENSOR SPECIFICATION INNOVATION SCORE",
    "SENSOR SPECIFICATION INNOVATION JUSTIFICATION",
    "SPATIAL RESOLUTION INNOVATION SCORE",
    "SPATIAL RESOLUTION INNOVATION JUSTIFICATION",
    "TECHNOLOGICAL BREAKTHROUGH SCORE",
    "TECHNOLOGICAL BREAKTHROUGH JUSTIFICATION",
    "NUMERIC TOTAL SCORE",
    "NUMERIC CONFIDENCE",
]

EVIDENCE_COLUMNS = [
    "ROW_ID",
    "SATNAME",
    "NORAD_ CAT_ID",
    "SOURCE_NAME",
    "SOURCE_URL",
    "MATCH_TYPE",
    "FIELD_GROUP",
    "SNIPPET",
    "STATUS",
]

KNOWN_COL_ALIASES = {
    "RA NAME": ["RA NAME", "RA Name", "RA_NAME", "ra_name"],
    "RA Name": ["RA Name", "RA NAME", "RA_NAME", "ra_name"],
    "INTLDES": ["INTLDES", "INTLDESIGNATOR", "International Designator", "OBJECT_ID"],
    "NORAD_ CAT_ID": ["NORAD_ CAT_ID", "NORAD CAT ID", "NORAD Number", "NORAD", "NORAD_CAT_ID"],
    "SATELLITE CODE": ["SATELLITE CODE", "Satellite Code", "SATELLITE_CODE"],
    "OBJECT_ TYPE": ["OBJECT_ TYPE", "OBJECT TYPE", "OBJECT_TYPE"],
    "SATNAME": ["SATNAME", "SATELLITE NAME", "Current Official Name of Satellite", "OBJECT_NAME", "satellite_name"],
    "MISSION NAME": ["MISSION NAME", "Mission Name", "MISSION_NAME"],
    "VEHICLE TYPE NAME": ["VEHICLE TYPE NAME", "Launch Vehicle", "VEHICLE_TYPE_NAME", "LAUNCH_VEHICLE"],
    "REGION": ["REGION", "Region"],
    "COUNTRY": ["COUNTRY", "Country", "Country of Operator/Owner", "OWNER", "OWNER_NAME"],
    "LAUNCH DATE": ["LAUNCH DATE", "Date of Launch", "Launch Date", "LAUNCH_DATE"],
    "LAUNCH_ YEAR": ["LAUNCH_ YEAR", "LAUNCH YEAR", "Launch Year"],
    "LAUNCH_ NUM": ["LAUNCH_ NUM", "LAUNCH NUM", "Launch Number"],
    "LAUNCH_ PIECE": ["LAUNCH_ PIECE", "Launch Piece"],
    "SITE": ["SITE", "Launch Site", "LAUNCH_SITE"],
    "DECAY": ["DECAY", "Decay Date", "DECAY_DATE"],
    "PERIOD": ["PERIOD"],
    "INCLINATION": ["INCLINATION"],
    "APOGEE": ["APOGEE"],
    "PERIGEE": ["PERIGEE"],
    "RCS_SIZE": ["RCS_SIZE", "RCS", "RCS_SIZE_M2"],
    "ALTITUDE": ["ALTITUDE", "Altitude"],
    "Class of Orbit": ["Class of Orbit"],
    "Type of Orbit": ["Type of Orbit"],
    "Users": ["Users", "users"],
    "Operator/Owner": ["Operator/Owner", "operator_owner"],
    "Purpose": ["Purpose", "purpose"],
    "Detailed Purpose": ["Detailed Purpose", "detailed_purpose"],
    "Comments": ["Comments", "comments", "Other Insights/ Comments"],
    "Launch Mass (kg.)": ["Launch Mass (kg.)", "Launch Mass (kg)", "Launch Mass", "Launch Mass kg"],
    "Dry Mass (kg.)": ["Dry Mass (kg.)", "Dry Mass (kg)", "Dry Mass"],
    "Expected Lifetime (yrs.)": ["Expected Lifetime (yrs.)", "Expected Lifetime", "Design Life"],
    "Contractor": ["Contractor"],
    "Country of Contractor": ["Country of Contractor"],
    "Sensor Specifications (if applicable)": ["Sensor Specifications (if applicable)", "Sensor Specifications", "sensor_specs"],
    "Spectral Bands": ["Spectral Bands", "spectral_bands"],
    "Spatial Resolution": ["Spatial Resolution", "spatial_resolution"],
    "Technological breakthroughs": ["Technological breakthroughs", "Technological Breakthroughs", "technological_breakthroughs"],
    "No. of payloads": ["No. of payloads", "Number of Payloads"],
    "SATELLITE Vehicle Launch Cost by NextSpaceFlight (in $ million) in launch year": [
        "SATELLITE Vehicle Launch Cost by NextSpaceFlight (in $ million) in launch year",
        "Launch Cost ($M)",
        "Vehicle Launch Cost",
    ],
    "Max Launch Mass of Vehicle to LEO (Kg)": ["Max Launch Mass of Vehicle to LEO (Kg)", "Max Launch Mass to LEO", "MAX_LEO_KG"],
    "Actual Launch Mass Carried by the Vehicle (Kg)": [
        "Actual Launch Mass Carried by the Vehicle (Kg)",
        "Actual Launch Mass Carried by the Vehicle",
        "Actual Launch Mass",
    ],
    "VEHICLE RESUABILITY (0/1)": ["VEHICLE RESUABILITY (0/1)", "Vehicle Reusability"],
    "Vehicle Resubaility Details (First stage/ second stage/ or more)": [
        "Vehicle Resubaility Details (First stage/ second stage/ or more)",
        "Vehicle Reusability Details",
    ],
    "Vehicle Resuability Source": ["Vehicle Resuability Source", "Vehicle Reusability Source"],
    "MISSION COST (Overall Mission Cost, Vehicle (Launch) Cost, Development Cost, Approved Cost, Operational Cost) by Official instutiuons or Space Agencies": [
        "MISSION COST (Overall Mission Cost, Vehicle (Launch) Cost, Development Cost, Approved Cost, Operational Cost) by Official instutiuons or Space Agencies",
        "MISSION COST",
        "Mission Cost",
    ],
    "SATELLITE Cost by Govt/ Parliament/ Space Agency (in $ million) in launch year": [
        "SATELLITE Cost by Govt/ Parliament/ Space Agency (in $ million) in launch year",
        "Satellite Development Cost",
    ],
    "MISSION/SATELLITE Cost by Other / News/ Wiklipedia sources (in $ million) in launch year": [
        "MISSION/SATELLITE Cost by Other / News/ Wiklipedia sources (in $ million) in launch year",
        "Other Reported Cost",
    ],
    "COST Reference": ["COST Reference", "Cost Reference"],
    "Other Insights/ Comments": ["Other Insights/ Comments", "Comments", "Other Comments"],
}

COUNTRY_OWNER_MAP = {
    "USA": "United States",
    "US": "United States",
    "PRC": "People's Republic of China",
    "CHN": "People's Republic of China",
    "CIS": "Former Soviet Union (Russia)",
    "RUS": "Russia",
    "IND": "India",
    "JPN": "Japan",
    "ESA": "European Space Agency",
    "EUM": "EUMETSAT",
    "UK": "United Kingdom",
    "FGER": "French Guiana",
    "GER": "Germany",
    "FR": "France",
    "CAN": "Canada",
    "AUS": "Australia",
    "ISR": "Israel",
    "KOR": "South Korea",
    "UAE": "United Arab Emirates",
    "TWN": "Taiwan",
    "SGP": "Singapore",
    "ARGN": "Argentina",
    "BRAZ": "Brazil",
    "MEX": "Mexico",
    "NETH": "Netherlands",
    "SPN": "Spain",
    "IT": "Italy",
    "BEL": "Belgium",
    "POL": "Poland",
    "UAE": "United Arab Emirates",
}

COUNTRY_REGION_MAP = {
    "India": "Asia",
    "Japan": "Asia",
    "People's Republic of China": "Asia",
    "China": "Asia",
    "Indonesia": "Asia",
    "Singapore": "Asia",
    "South Korea": "Asia",
    "Taiwan": "Asia",
    "Israel": "Asia",
    "United Arab Emirates": "Asia",
    "Russia": "Europe/Asia",
    "Former Soviet Union (Russia)": "Europe/Asia",
    "European Space Agency": "Europe",
    "EUMETSAT": "Europe",
    "United Kingdom": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Canada": "North America",
    "United States": "North America",
    "Mexico": "North America",
    "Argentina": "South America",
    "Brazil": "South America",
    "Netherlands": "Europe",
    "Spain": "Europe",
    "Italy": "Europe",
    "Belgium": "Europe",
    "Poland": "Europe",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    "South Africa": "Africa",
    "Nigeria": "Africa",
    "Egypt": "Africa",
}
